language: r
cache: packages
pandoc_version: 2.6

branches:
  only: source

script:
  - Rscript -e 'devtools::install_github("bbc/bbplot", force=T)'
  - Rscript -e 'servr:::knit_maybe(c(".", "_source", "_posts"), c(".", "_posts", "_posts"), "build.R", "jekyll")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  target_branch: master